name: Auto Merge PR

permissions:
  pull-requests: write
  contents: write
  checks: write
  statuses: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'chenylon'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Output GH_TOKEN
        run: |
          echo "GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

      # - name: Auto approve PR
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr review "$PR_URL" --approve

      - name: Auto Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge "$PR_URL" --auto --merge 