name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # 只对特定用户的 PR 执行
    if: github.event.pull_request.user.login == 'chenylon'
    
    # 添加权限设置
    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Merge PR
        run: |
          # 验证 token 是否存在
          if [ -z "${{ secrets.ACTION_TOKEN }}" ]; then
            echo "错误：ACTION_TOKEN 未设置"
            exit 1
          fi
          
          echo "开始认证 GitHub CLI..."
          # 设置超时时间
          timeout 5m gh auth login --with-token <<< "${{ secrets.ACTION_TOKEN }}"
          
          echo "开始尝试合并 PR #${{ github.event.pull_request.number }}..."
          # 添加错误处理
          if ! gh pr merge ${{ github.event.pull_request.number }} --auto --merge; then
            echo "自动合并失败，请检查 PR 状态"
            exit 1
          fi
          
          echo "PR 合并成功！"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}  # 添加 GH_TOKEN