name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # 只对特定用户的 PR 执行
    if: github.event.pull_request.user.login == 'chenylon'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Merge PR
        run: |
          # 使用 GitHub CLI 进行自动合并
          gh auth login --with-token <<< "${{ secrets.ACTION_TOKEN }}"
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }} 