name: Auto Merge PR

permissions:
  pull-requests: write
  contents: write
  checks: write
  statuses: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'chenylon'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Approve PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr review --approve ${{ github.event.pull_request.number }}

      - name: Auto Merge PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge 