name: Auto Merge PR

permissions:
  pull-requests: write
  contents: write
  checks: write
  statuses: write
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'chenylon'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      
      - name: Output GH_TOKEN
        run: |
          echo "GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

      - name: Auto approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr review "$PR_URL" --approve

      - name: Auto Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge "$PR_URL" --auto --merge 